name: Docker

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    name: Docker

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if docker image build is working
        run: docker build -f Dockerfile .
