name: Jest

on:
  pull_request:
    branches: [main]

jobs:
  jest-run:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: yarn install --ignore-optional

      - name: Run Jest
        run: yarn test:jest
